name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libsdl2-dev libsdl2-image-dev

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install sdl2 sdl2_image

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: C:\vcpkg\vcpkg.exe install --triplet x64-windows sdl2 sdl2-image

    - name: Configure CMake
      if: matrix.os != 'windows-latest'
      run: cmake -B ${{github.workspace}}/build

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows

    - name: Build
      run: cmake --build ${{github.workspace}}/build

